// ALERTS

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";

// PROJECTS
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const UPDATE_PROECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECT_ERROR = "PROJECT_ERRORS";
export const CLEAR_PROJECT = "CLEAR_PROJECT";
